"""add ra dec to observation_request_position

Revision ID: 0fa985956225
Revises: c9c1a11bca46
Create Date: 2025-12-25 13:49:01.091692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa985956225'
down_revision = 'c9c1a11bca46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_request_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ra_h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ra_m', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ra_s', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec_sign', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('dec_d', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dec_m', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dec_s', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_request_position', schema=None) as batch_op:
        batch_op.drop_column('dec_s')
        batch_op.drop_column('dec_m')
        batch_op.drop_column('dec_d')
        batch_op.drop_column('dec_sign')
        batch_op.drop_column('ra_s')
        batch_op.drop_column('ra_m')
        batch_op.drop_column('ra_h')

    # ### end Alembic commands ###
