"""Add observation request

Revision ID: 909f171d611e
Revises: 22afc9f0df9a
Create Date: 2024-10-04 22:19:32.094888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909f171d611e'
down_revision = '22afc9f0df9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lattitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('observatory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('telescope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('observatory_id', sa.Integer(), nullable=False),
    sa.Column('aperature_mm', sa.Float(), nullable=False),
    sa.Column('focal_length_mm', sa.Float(), nullable=False),
    sa.Column('camera_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['observatory_id'], ['observatory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('observations_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telescope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['telescope_id'], ['telescope.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations_request')
    op.drop_table('telescope')
    op.drop_table('observatory')
    op.drop_table('site')
    # ### end Alembic commands ###
