"""Ergaenzung row /Column,Mosaik, RA DEC  bei Formular

Revision ID: 9fd5e5447a64
Revises: 0fa985956225
Create Date: 2026-01-25 16:46:08.704821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd5e5447a64'
down_revision = '0fa985956225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('georg_request')
    op.drop_table('georg_request_row')
    op.drop_table('_alembic_tmp_observation_request')
    with op.batch_alter_table('observation_request', schema=None) as batch_op:
        batch_op.alter_column('request_purpose',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_request', schema=None) as batch_op:
        batch_op.alter_column('request_purpose',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('_alembic_tmp_observation_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('request_date', sa.DATETIME(), nullable=False),
    sa.Column('request_observatory_id', sa.INTEGER(), nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('request_purpose', sa.VARCHAR(length=100), nullable=False),
    sa.Column('request_poweruser_id', sa.INTEGER(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['request_observatory_id'], ['observatory.id'], ),
    sa.ForeignKeyConstraint(['request_poweruser_id'], ['poweruser.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('georg_request_row',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), nullable=False),
    sa.Column('row_index', sa.INTEGER(), nullable=False),
    sa.Column('aufnahmeanzahl', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bulbtime', sa.VARCHAR(length=50), nullable=True),
    sa.Column('filter', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dithering', sa.BOOLEAN(), nullable=False),
    sa.Column('gain', sa.VARCHAR(length=50), nullable=True),
    sa.Column('offset', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['georg_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('georg_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('beginndatum', sa.VARCHAR(length=20), nullable=True),
    sa.Column('beginnuhrzeit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('enddatum', sa.VARCHAR(length=20), nullable=True),
    sa.Column('enduhrzeit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('teleskop', sa.VARCHAR(length=200), nullable=True),
    sa.Column('objektkategorie', sa.VARCHAR(length=200), nullable=True),
    sa.Column('objectname', sa.TEXT(), nullable=True),
    sa.Column('motivation', sa.TEXT(), nullable=True),
    sa.Column('ra_h', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ra_m', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ra_s', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dec_sign', sa.VARCHAR(length=2), nullable=True),
    sa.Column('dec_d', sa.VARCHAR(length=10), nullable=True),
    sa.Column('dec_m', sa.VARCHAR(length=10), nullable=True),
    sa.Column('dec_s', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
