"""Remove unnecessary attributes

Revision ID: c494cc8daa7c
Revises: ddd71659bb6e
Create Date: 2024-08-10 18:23:21.017904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c494cc8daa7c'
down_revision = 'ddd71659bb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')
        batch_op.drop_column('isPowerUser')
        batch_op.drop_column('isApprover')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApprover', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('isPowerUser', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('isAdmin', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
