"""Remove NOT NULL constraint from request_purpose

Revision ID: c9c1a11bca46
Revises: 31c169b125dc
Create Date: 2025-11-26 18:26:22.772989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c1a11bca46'
down_revision = '31c169b125dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_observation_request')
    with op.batch_alter_table('observation_request', schema=None) as batch_op:
        batch_op.alter_column('request_purpose',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    with op.batch_alter_table('observation_request', schema=None) as batch_op:
        batch_op.alter_column('request_purpose',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.create_table('import_observation_request',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('Status', sa.TEXT(), nullable=True),
    sa.Column('Antragsdatum', sa.TEXT(), nullable=True),
    sa.Column('Beobachter', sa.TEXT(), nullable=True),
    sa.Column('E-Mail-Adresse', sa.TEXT(), nullable=True),
    sa.Column('Mitgliedsnummer', sa.TEXT(), nullable=True),
    sa.Column('Beobachtungs-Datum', sa.TEXT(), nullable=True),
    sa.Column('Dauer_der_Belegung', sa.TEXT(), nullable=True),
    sa.Column('Wunsch-Betreuer', sa.TEXT(), nullable=True),
    sa.Column('Gruppen-Einzelbeobachtung', sa.TEXT(), nullable=True),
    sa.Column('Teleskop', sa.TEXT(), nullable=True),
    sa.Column('Name_des_Objekts', sa.TEXT(), nullable=True),
    sa.Column('Art_des_Objekts', sa.TEXT(), nullable=True),
    sa.Column('Ziel_der_Beobachtung', sa.TEXT(), nullable=True),
    sa.Column('Mondphase', sa.TEXT(), nullable=True),
    sa.Column('Filter', sa.TEXT(), nullable=True),
    sa.Column('Einzelbelichtungen', sa.TEXT(), nullable=True),
    sa.Column('Anzahl_Aufnahmen', sa.TEXT(), nullable=True),
    sa.Column('Gesamtbelichtung', sa.TEXT(), nullable=True),
    sa.Column('Remark', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
