"""Yves: row/columnt/mosaic/RA/Dec in Formular

Revision ID: d0747670b9e5
Revises: 31c169b125dc
Create Date: 2026-01-30 18:33:38.699580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0747670b9e5'
down_revision = '31c169b125dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_request_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mosaic', sa.Boolean(), nullable=False, server_default="False"))
        batch_op.add_column(sa.Column('ra_h', sa.Integer(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column('ra_m', sa.Integer(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column('ra_s', sa.Float(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column('dec_sign', sa.String(length=1), nullable=True, server_default="+"))
        batch_op.add_column(sa.Column('dec_d', sa.Integer(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column('dec_m', sa.Integer(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column('dec_s', sa.Float(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column('block_no', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('row_in_block', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_request_position', schema=None) as batch_op:
        batch_op.drop_column('row_in_block')
        batch_op.drop_column('block_no')
        batch_op.drop_column('dec_s')
        batch_op.drop_column('dec_m')
        batch_op.drop_column('dec_d')
        batch_op.drop_column('dec_sign')
        batch_op.drop_column('ra_s')
        batch_op.drop_column('ra_m')
        batch_op.drop_column('ra_h')
        batch_op.drop_column('mosaic')

    # ### end Alembic commands ###
