"""Add filter priority (for sorting)

Revision ID: d68321ef59ce
Revises: 9933de15e3ed
Create Date: 2026-08-30 15:52:29.352615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68321ef59ce'
down_revision = '9933de15e3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filterset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filterset', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
