"""Initial migration

Revision ID: e7a47718181b
Revises: 
Create Date: 2026-03-15 12:48:09.538039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a47718181b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=False),
    sa.Column('maintainer', sa.String(length=100), nullable=False),
    sa.Column('equinoxes', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogue_meta')),
    sa.UniqueConstraint('name', name=op.f('uq_catalogue_meta_name')),
    sqlite_autoincrement=True
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group')),
    sa.UniqueConstraint('name', name=op.f('uq_group_name')),
    sqlite_autoincrement=True
    )
    op.create_table('motivation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Motivation', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_motivation_types')),
    sa.UniqueConstraint('Motivation', name=op.f('uq_motivation_types_Motivation')),
    sqlite_autoincrement=True
    )
    op.create_table('object_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Objecttype', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_types')),
    sa.UniqueConstraint('Objecttype', name=op.f('uq_object_types_Objecttype')),
    sqlite_autoincrement=True
    )
    op.create_table('observation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Datum', sa.String(length=25), nullable=False),
    sa.Column('Objekt', sa.String(length=80), nullable=True),
    sa.Column('Rubrik', sa.String(length=160), nullable=True),
    sa.Column('Teleskop', sa.String(length=100), nullable=True),
    sa.Column('EinzelbelichtungSekunden', sa.String(length=60), nullable=True),
    sa.Column('Bildanzahl', sa.String(length=5), nullable=True),
    sa.Column('Filter', sa.String(length=60), nullable=True),
    sa.Column('Bildersteller', sa.String(length=80), nullable=True),
    sa.Column('Observer', sa.String(length=80), nullable=True),
    sa.Column('NeuentdeckteKleinplaneten', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_history')),
    sqlite_autoincrement=True
    )
    op.create_table('poweruser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mobilfone', sa.String(length=20), nullable=False),
    sa.Column('fone', sa.String(length=20), nullable=True),
    sa.Column('Einweisung', sa.String(length=30), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poweruser')),
    sa.UniqueConstraint('email', name=op.f('uq_poweruser_email')),
    sa.UniqueConstraint('name', name=op.f('uq_poweruser_name')),
    sqlite_autoincrement=True
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name')),
    sqlite_autoincrement=True
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lattitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site')),
    sa.UniqueConstraint('name', name=op.f('uq_site_name')),
    sqlite_autoincrement=True
    )
    op.create_table('system_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_parameters')),
    sa.UniqueConstraint('parameter', name=op.f('uq_system_parameters_parameter')),
    sqlite_autoincrement=True
    )
    op.create_table('system_parameters_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('history_reason', sa.String(length=1), nullable=False),
    sa.Column('history_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_parameters_history')),
    sqlite_autoincrement=True
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('surname', sa.String(length=40), nullable=True),
    sa.Column('firstname', sa.String(length=40), nullable=True),
    sa.Column('vds_number', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('name', name=op.f('uq_user_name')),
    sqlite_autoincrement=True
    )
    op.create_table('catalogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalogue_meta_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('long_name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_meta_id'], ['catalogue_meta.id'], name=op.f('fk_catalogue_catalogue_meta_id_catalogue_meta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogue')),
    sa.UniqueConstraint('name', name=op.f('uq_catalogue_name')),
    sqlite_autoincrement=True
    )
    op.create_table('observatory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_observatory_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observatory')),
    sa.UniqueConstraint('name', name=op.f('uq_observatory_name')),
    sqlite_autoincrement=True
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_post_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post')),
    sqlite_autoincrement=True
    )
    op.create_table('role_group',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_role_group_group_id_group')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_group_role_id_role'))
    )
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_user_group_group_id_group')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_group_user_id_user'))
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_preferences_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sqlite_autoincrement=True
    )
    op.create_table('observation_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('request_observatory_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=10), nullable=False),
    sa.Column('request_poweruser_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['request_observatory_id'], ['observatory.id'], name=op.f('fk_observation_request_request_observatory_id_observatory')),
    sa.ForeignKeyConstraint(['request_poweruser_id'], ['user.id'], name=op.f('fk_observation_request_request_poweruser_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_observation_request_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_request')),
    sqlite_autoincrement=True
    )
    op.create_table('telescope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('observatory_id', sa.Integer(), nullable=True),
    sa.Column('aperature_mm', sa.Float(), nullable=False),
    sa.Column('focal_length_mm', sa.Float(), nullable=False),
    sa.Column('camera_name', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['observatory_id'], ['observatory.id'], name=op.f('fk_telescope_observatory_id_observatory')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telescope')),
    sa.UniqueConstraint('name', name=op.f('uq_telescope_name')),
    sqlite_autoincrement=True
    )
    op.create_table('filterset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('telescope_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['telescope_id'], ['telescope.id'], name=op.f('fk_filterset_telescope_id_telescope')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filterset')),
    sqlite_autoincrement=True
    )
    op.create_table('observation_request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('subtype', sa.String(length=10), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['observation_request.id'], name=op.f('fk_observation_request_log_order_id_observation_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_request_log')),
    sqlite_autoincrement=True
    )
    op.create_table('poweruser_meldung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_request_id', sa.Integer(), nullable=False),
    sa.Column('poweruser_user_id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('availability IN (1,2,3)', name=op.f('ck_poweruser_meldung_ck_availability_1_2_3')),
    sa.ForeignKeyConstraint(['observation_request_id'], ['observation_request.id'], name=op.f('fk_poweruser_meldung_observation_request_id_observation_request')),
    sa.ForeignKeyConstraint(['poweruser_user_id'], ['user.id'], name=op.f('fk_poweruser_meldung_poweruser_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poweruser_meldung')),
    sa.UniqueConstraint('observation_request_id', 'poweruser_user_id', name='uq_meldung_request_poweruser'),
    sqlite_autoincrement=True
    )
    op.create_table('observation_request_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_request_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('telescope_id', sa.Integer(), nullable=False),
    sa.Column('filterset_id', sa.Integer(), nullable=True),
    sa.Column('target_objecttype', sa.String(length=200), nullable=True),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('target_coordinates', sa.String(length=200), nullable=True),
    sa.Column('target_coordinates_lock', sa.String(length=1), nullable=True),
    sa.Column('exposure_count', sa.Integer(), nullable=True),
    sa.Column('exposure_time', sa.Integer(), nullable=True),
    sa.Column('mosaic', sa.Boolean(), nullable=False),
    sa.Column('exposure_gain', sa.Integer(), nullable=True),
    sa.Column('exposure_offset', sa.Integer(), nullable=True),
    sa.Column('exposure_dither', sa.Integer(), nullable=True),
    sa.Column('exposure_focus', sa.Integer(), nullable=True),
    sa.Column('exposure_starttime', sa.Time(), nullable=True),
    sa.Column('ra_h', sa.Integer(), nullable=True),
    sa.Column('ra_m', sa.Integer(), nullable=True),
    sa.Column('ra_s', sa.Float(), nullable=True),
    sa.Column('dec_sign', sa.String(length=1), nullable=True),
    sa.Column('dec_d', sa.Integer(), nullable=True),
    sa.Column('dec_m', sa.Integer(), nullable=True),
    sa.Column('dec_s', sa.Float(), nullable=True),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('row_in_block', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filterset_id'], ['filterset.id'], name=op.f('fk_observation_request_position_filterset_id_filterset')),
    sa.ForeignKeyConstraint(['observation_request_id'], ['observation_request.id'], name=op.f('fk_observation_request_position_observation_request_id_observation_request')),
    sa.ForeignKeyConstraint(['telescope_id'], ['telescope.id'], name=op.f('fk_observation_request_position_telescope_id_telescope')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_request_position')),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_request_position')
    op.drop_table('poweruser_meldung')
    op.drop_table('observation_request_log')
    op.drop_table('filterset')
    op.drop_table('telescope')
    op.drop_table('observation_request')
    op.drop_table('user_preferences')
    op.drop_table('user_group')
    op.drop_table('role_group')
    op.drop_table('post')
    op.drop_table('observatory')
    op.drop_table('catalogue')
    op.drop_table('user')
    op.drop_table('system_parameters_history')
    op.drop_table('system_parameters')
    op.drop_table('site')
    op.drop_table('role')
    op.drop_table('poweruser')
    op.drop_table('observation_history')
    op.drop_table('object_types')
    op.drop_table('motivation_types')
    op.drop_table('group')
    op.drop_table('catalogue_meta')
    # ### end Alembic commands ###
