"""ObservationRequest points to poweruser in user table not poweruser table

Revision ID: faa7a397d722
Revises: 7e000cac9c41
Create Date: 2026-02-15 21:45:00.650036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa7a397d722'
down_revision = '7e000cac9c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('observation_request_request_poweruser_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['request_poweruser_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('observation_request_request_poweruser_id_fkey'), 'poweruser', ['request_poweruser_id'], ['id'])

    # ### end Alembic commands ###
